#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \
	less="less -r"

# These common commands are just too long! Abbreviate them.
alias \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	ll="ls -alh" \
	lf="lfub" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
	chat="chat -m $XDG_DATA_HOME/chat/ggml-alpaca-7b-q4.bin"
