#!/bin/sh

# xinitrc runs automatically when you run startx

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

dwmblocks &
exec dwm

# Terminate already running bar instances
#killall -q polybar
# If all your bars have ipc enabled, you can also use
# polybar-msg cmd quit

# Launch Polybar, using default config location ~/.config/polybar/config.ini
#polybar mybar 2>&1 | tee -a /tmp/polybar.log & disown
#exec bspwm
